apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-data
  namespace: production-poc
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi