apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: production-poc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      serviceAccountName: user-service

      containers:
        - name: user-service
          image: nginx
          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi

          volumeMounts:
            - name: user-data
              mountPath: /data

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10

      volumes:
        - name: user-data
          persistentVolumeClaim:
            claimName: user-data

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: production-poc
spec:
  selector:
    app: user-service
  ports:
    - port: 80
      targetPort: 80