apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-resources-binding
  namespace: rbac-poc
subjects:
  - kind: ServiceAccount
    name: developer
    namespace: rbac-poc
roleRef:
  kind: Role
  name: developer-resources-role
  apiGroup: rbac.authorization.k8s.io