apiVersion: v1
kind: Service
metadata:
  name: node-k8s-service
spec:
  selector:
    app: node-k8s
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP


# Service
#    │
#    │ finds Pods with app=node-k8s
#    │
#    ├── Pod 1
#    └── Pod 2
# This is how the Service knows which Pods to send traffic to.


# Port:
# Mac localhost:3000
#         ↓
# kubectl port-forward
#         ↓
# Kubernetes Service:3000
#         ↓
# Pod:3000
#         ↓
# Node.js:3000

